steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_COMPANY=${_NEXT_PUBLIC_COMPANY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PARENT_COMPANY=${_NEXT_PUBLIC_PARENT_COMPANY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPPORT_EMAIL=${_NEXT_PUBLIC_SUPPORT_EMAIL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'ENCRYPTION_KEY=${_ENCRYPTION_KEY}'
      - '--build-arg'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - '--build-arg'
      - 'SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}'
      - '--build-arg'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_S3_STORAGE_URL=${_NEXT_PUBLIC_S3_STORAGE_URL}'
      - '--build-arg'
      - 'S3_ACCESS_KEY=${_S3_ACCESS_KEY}'
      - '--build-arg'
      - 'S3_SECRET_KEY=${_S3_SECRET_KEY}'
      - '--build-arg'
      - 'S3_REGION=${_S3_REGION}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GRAPHQL_URL=${_NEXT_PUBLIC_GRAPHQL_URL}'
      - '--build-arg'
      - 'DB_URL=${_DB_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_INBUCKET_URL=${_NEXT_PUBLIC_INBUCKET_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STUDIO_URL=${_NEXT_PUBLIC_STUDIO_URL}'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/keyfate-frontend'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/keyfate-frontend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'keyfate-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/keyfate-frontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
images:
  - 'gcr.io/$PROJECT_ID/keyfate-frontend'
