# Use Node.js 22 Alpine as base image
FROM node:22-alpine AS base

# Install pnpm
RUN npm install -g pnpm

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app

# Copy package files from frontend directory
COPY frontend/package.json frontend/pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

# Accept build arguments
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_COMPANY
ARG NEXT_PUBLIC_PARENT_COMPANY
ARG NEXT_PUBLIC_SUPPORT_EMAIL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_API_URL
ARG ENCRYPTION_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG JWT_SECRET
ARG NEXT_PUBLIC_S3_STORAGE_URL
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_REGION
ARG NEXT_PUBLIC_GRAPHQL_URL
ARG DB_URL
ARG NEXT_PUBLIC_INBUCKET_URL
ARG NEXT_PUBLIC_STUDIO_URL

# Set environment variables for build
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_COMPANY=$NEXT_PUBLIC_COMPANY
ENV NEXT_PUBLIC_PARENT_COMPANY=$NEXT_PUBLIC_PARENT_COMPANY
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV NEXT_PUBLIC_S3_STORAGE_URL=$NEXT_PUBLIC_S3_STORAGE_URL
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY
ENV S3_SECRET_KEY=$S3_SECRET_KEY
ENV S3_REGION=$S3_REGION
ENV NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL
ENV DB_URL=$DB_URL
ENV NEXT_PUBLIC_INBUCKET_URL=$NEXT_PUBLIC_INBUCKET_URL
ENV NEXT_PUBLIC_STUDIO_URL=$NEXT_PUBLIC_STUDIO_URL

COPY --from=deps /app/node_modules ./node_modules
COPY frontend/ ./

# Copy supabase types to match TypeScript path alias (@/supabase/* -> ../supabase/*)
COPY supabase/database.types.ts ../supabase/database.types.ts
COPY supabase/types/ ../supabase/types/

# Build the application
RUN pnpm build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built application
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
